### ISSUE TITLE
Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by vjpr** [prey/prey-node-client#499]
```
/usr/local/lib/prey/current/bin/prey
```

```
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/prey/versions/1.8.3/lib/agent/cli.js:14:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by javo** [comment]
hi @vjpr when did this happen?

**Comment by vjpr** [comment]
I was following instructions to uninstall at command-line.

`prey config` etc..

**Comment by javo** [comment]
This command?
`sudo /usr/lib/prey/current/bin/prey config hooks pre_uninstall && sudo rm -rf /usr/lib/prey /var/log/prey.log /etc/prey`

Did you installed prey normally? You could try installing it again and run the uninstall command, it should work fine

**Comment by vjpr** [comment]
I already tried installing it again and still does not work.

**Comment by javo** [comment]
Try with this:
`sudo /usr/lib/prey/versions/1.9.10/bin/prey config hooks pre_uninstall && sudo rm -rf /usr/lib/prey /var/log/prey.log /etc/prey`
