### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by paxe** [prey/prey-node-client#503]
The README.md merely points to what to download, but I don't see any instructions on what to do afterwards.

Running prey-1.9.11/bin/prey gives:

module.js:538
    throw err;
    ^

Error: Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/dev/shm/prey-1.9.11/lib/agent/utils/storage.js:3:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by javo** [comment]
Hi @paxe 

Is this on Linux?

**Comment by paxe** [comment]
Yes, sorry for lack of details... Debian buster, which does have the sqlite3 package installed.

I also try running out of git repo, this gives:

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'commander'
...

**Comment by javo** [comment]
hi @paxe 
If you're running from the repo you have to install the dependencies
run `npm install`  on the path you have cloned the repository

**Comment by paxe** [comment]
Thanks, installing out of a repo worked after that, it would be good to put in the README or the like.
Or did I miss it somewhere?
