### ISSUE TITLE
Initial configuration fails.

### ISSUE THREAD

**Issue by rokejulianlockhart** [prey/prey-node-client#714]
```
rokejulianlockhart@localhost:~> script -a
Script started, output log file is 'typescript'.
```
The log is available [here]().
```
rokejulianlockhart@localhost:~> /home/rokejulianlockhart/Downloads/prey-linux-1.11.0-x64/prey-1.11.0/bin/prey

Looks like there's no config file yet. Glad to see you're getting started. :)
To finish setting up Prey, please run `prey config hooks post_install` as root.

```
```
rokejulianlockhart@localhost:~> sudo prey config hooks post_install
[sudo] password for root: 
sudo: prey: command not found
```
This is OpenSUSE Tumbleweed, so no `prey` executable exists in $PATH. This is obviously expected.
```
rokejulianlockhart@localhost:~> sudo /home/rokejulianlockhart/Downloads/prey-linux-1.11.0-x64/prey-1.11.0/bin/prey config hooks post_install
Creating user prey...
Creating a user called prey
Giving prey user passwordless sudo priviledges...
Creating config dir: /etc/prey
Touching log file: /var/log/prey.log
Setting permissions on /home/rokejulianlockhart/Downloads/prey-linux-1.11.0-x64/prey-1.11.0
Getting IDs for user prey and group prey
EXCEPTION! The "uid" argument must be of type number. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "uid" argument must be of type number. Received undefined
    at Object.lchown (node:fs:1889:3)
    at chown (/home/rokejulianlockhart/Downloads/prey-linux-1.11.0-x64/prey-1.11.0/node_modules/chownr/chownr.js:69:13)
    at chownrKid (/home/rokejulianlockhart/Downloads/prey-linux-1.11.0-x64/prey-1.11.0/node_modules/chownr/chownr.js:94:5)
    at /home/rokejulianlockhart/Downloads/prey-linux-1.11.0-x64/prey-1.11.0/node_modules/chownr/chownr.js:123:31
    at Array.forEach (<anonymous>)
    at /home/rokejulianlockhart/Downloads/prey-linux-1.11.0-x64/prey-1.11.0/node_modules/chownr/chownr.js:123:14
    at node:fs:192:23
    at node:internal/util:453:5
    at getDirents (node:internal/fs/utils:279:7)
    at FSReqCallback.req.oncomplete (node:fs:1415:7)
rokejulianlockhart@localhost:~>
```
...demonstrates the problem.

**Comment by JohaoRosasRosillo** [comment]
@rokejulianlockhart for install prey rin ubuntu read this please https://help.preyproject.com/article/292-install-prey-on-ubuntu-or-any-other-debian-based-distribution

**Comment by rokejulianlockhart** [comment]
@JohaoRosasRosillo, that's useless to me, because I'm using OpenSUSE.
