### ISSUE TITLE
Error: Cannot find module 'satan'

### ISSUE THREAD

**Issue by blackjid** [prey/prey-node-client#76]
Any idea? I cannot install prey on OSX (yosemite). It fails with this..

```shell
npm ERR! fetch failed https://registry.npmjs.org/minstache/-/minstache-1.2.0.tgz

> prey@1.3.6 preuninstall /opt/boxen/nodenv/versions/0.10.28/lib/node_modules/prey
> ./bin/prey config hooks pre_uninstall


module.js:340
    throw err;
    ^
Error: Cannot find module 'satan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/boxen/nodenv/versions/0.10.28/lib/node_modules/prey/lib/conf/tasks/daemon.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm http 200 https://registry.npmjs.org/launchd/-/launchd-0.0.5.tgz
npm http 200 https://registry.npmjs.org/batch/-/batch-0.5.1.tgz

```

**Comment by lemavri** [comment]
According to the log it seems there was an error fetching the `minstache` package. Have you tried to install prey once again? If you did and the problem persist, can you please manually run `npm install satan` and let me know how it goes?

**Comment by lemavri** [comment]
I will close the issue. Please, if you stumble into the problem again, don't hesitate to re-open it.

**Comment by blackjid** [comment]
Hey @lemavri I think you were right. Probably was a connection problem, I tried again after a few hours, and it worked fine.

**Comment by lemavri** [comment]
Cool. Thanks for reporting back :)
